export const WOMAN_DATA = [
  {
    img: "/images/womenproducts/w2.png",
    name: "Floral Print Short Sleeves Nightgown",
    price: 699,
    rating: " 4.7(428)",
    idtype: "eye",
    prodID: "1",
  },
  {
    img: "/images/womenproducts/w3.jpg",
    name: " Printed Short Sleeves Chemise - Pack of 2",
    price: 299,
    rating: " 4.7(53)",
    idtype: "combo",
    prodID: "2",
  },
  {
    img: "/images/womenproducts/w4.jpg",
    name: " Textured Sports Shoes",
    price: 399,
    idtype: "eye",
    rating: " 4.6",
  },
  {
    img: "/images/womenproducts/w5.jpg",
    name: "Printed Layered Flutter Sleeve A-line Dress",

    price: 99,
    idtype: "combo",
    rating: "4.9",
  },
  {
    img: "/images/womenproducts/w6.jpg",
    name: "MAX Women Striped Shirt Dress",
    price: 399,
    idtype: "foundation",
    rating: " 4.9",
  },
  {
    img: "/images/womenproducts/w7.jpg",
    name: "Printed Round Neck T-shirt with Elasticated Pyjamas",
    price: 199,
    idtype: "foundation",
    rating: "4.8",
  },
  {
    img: "/images/womenproducts/w8.jpg",
    name: "Striped Shirt Dress",
    price: 599,
    idtype: "eye",
    rating: "4.8",
  },
  {
    img: "/images/womenproducts/w9.jpg",
    name: "MAX Women Textured Sports Shoes",
    price: 99,
    idtype: "foundation",
    rating: " 4.8",
  },
  {
    img: "/images/womenproducts/w10.jpg",
    name: " Floral Printed High Neck A-line",
    price: 399,
    rating: "4.7",
    idtype: "combo",
  },
  {
    img: "/images/womenproducts/w11.jpg",
    name: "Printed A-Line Dress",
    price: 599,
    rating: "4.7",
    idtype: "combo",
  },
  {
    img: "/images/womenproducts/w12.jpg",
    name: "Printed Short Sleeves Nightgown",
    price: 879,
    rating: "4.7",
    idtype: "combo",
  },
  {
    img: "/images/womenproducts/w1.jpg",
    name: "Printed Pyjamas - Set Of 2",
    price: 129,
    rating: "4.7",
    idtype: "combo",
  },
  {
    img: "/images/womenproducts/w1.jpg",
    name: "Striped Laced-Up Shoes",
    price: 99,
    rating: "4.7",
    idtype: "combo",
  },
  {
    img: "/images/womenproducts/maxwomen-shoes-flatsandals.jpg",
    name: "Flatsandals",
    price: 599,
    rating: "4.7",
    idtype: "combo",
  },
  {
    img: "/images/womenproducts/maxwomen-shoes-casualshoes.jpg",
    name: "Casualshoes",
    price: 899,
    rating: "4.7",
    idtype: "combo",
  },
  {
    img: "/images/womenproducts/maxwomen-shoes-flipflops.jpg",
    name: "Flipflops",
    price: 199,
    rating: "4.7",
    idtype: "combo",
  },
];
